--1a.
CREATE TABLE FIGURY(
    ID NUMBER(1) PRIMARY KEY,
    KSZTALT MDSYS.SDO_GEOMETRY);
--b.
INSERT INTO FIGURY(ID, KSZTALT)
VALUES(1, MDSYS.SDO_GEOMETRY(
    2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,4), MDSYS.SDO_ORDINATE_ARRAY(3,5, 7,5, 5,3)
    ));
INSERT INTO FIGURY(ID, KSZTALT)
VALUES(2, MDSYS.SDO_GEOMETRY(
    2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3), MDSYS.SDO_ORDINATE_ARRAY(1,1, 5,5)
    ));
INSERT INTO FIGURY(ID, KSZTALT)
VALUES(3, MDSYS.SDO_GEOMETRY(
    2002, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1,4,2, 1,2,1, 5,2,2), MDSYS.SDO_ORDINATE_ARRAY(3,2, 6,2, 7,3, 8,2, 7,1)
    ));
--c.
INSERT INTO FIGURY(ID, KSZTALT)
VALUES(4, MDSYS.SDO_GEOMETRY(
    2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,4), MDSYS.SDO_ORDINATE_ARRAY(3,3, 7,3, 10,3)
    ));
--d.
SELECT ID, SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT, 0.001) AS VAL FROM FIGURY;
--e.
DELETE FROM FIGURY WHERE SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT, 0.001) != 'TRUE';
--f.
COMMIT;