--1.
CREATE TABLE CYTATY AS
SELECT * FROM ZSBD_TOOLS.cytaty;

--2.
SELECT AUTOR, TEKST
FROM CYTATY
WHERE UPPER(TEKST) LIKE '%PESYMISTA%' AND UPPER(TEKST) LIKE '%OPTYMISTA%';

--3.
CREATE INDEX CYTATY_IDX ON CYTATY(TEKST) INDEXTYPE IS CTXSYS.CONTEXT;

--4.
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'pesymista and optymista') > 0;

--5.
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'pesymista ~ optymista') > 0;

--6.
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'near((pesymista, optymista), 3)') > 0;

--7.
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'near((pesymista, optymista), 10)') > 0;

--8.
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'życi%') > 0;

--9.
SELECT AUTOR, TEKST, SCORE(1)
FROM CYTATY
WHERE CONTAINS(TEKST, 'życi%', 1) > 0;

--10.
SELECT AUTOR, TEKST, SCORE(1) AS DOPASOWANIE
FROM CYTATY
WHERE CONTAINS(TEKST, 'życi%', 1) > 0
ORDER BY DOPASOWANIE DESC
FETCH FIRST 1 ROW ONLY;

--11.
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'fuzzy(probelm,,,N)') > 0;

--12.
INSERT INTO CYTATY VALUES(39, 'Bertrand Russell', 'To smutne, że głupcy są tacy pewni siebie, a ludzie rozsądni tacy pełni wątpliwości');
COMMIT;

--13.
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'głupcy') > 0;

-- Indeks jest niezaktualizowany, więc zapytanie nie zawiera nowo dodanych wierszy

--14.
SELECT *
FROM DR$CYTATY_IDX$I;

SELECT *
FROM DR$CYTATY_IDX$I
WHERE TOKEN_TEXT = 'GŁUPCY';

--15.
DROP INDEX CYTATY_IDX;

CREATE INDEX CYTATY_IDX ON CYTATY(TEKST) INDEXTYPE IS CTXSYS.CONTEXT;

--16.
SELECT *
FROM DR$CYTATY_IDX$I
WHERE TOKEN_TEXT = 'GŁUPCY';

SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'głupcy') > 0;

--17.
DROP INDEX CYTATY_IDX;
DROP TABLE CYTATY;



--Zaawansowane indeksowanie i wyszukiwanie
--1.
CREATE TABLE QUOTES AS
SELECT * FROM ZSBD_TOOLS.quotes;

--2.
CREATE INDEX QUOTES_IDX ON QUOTES(TEXT) INDEXTYPE IS CTXSYS.CONTEXT;

--3.
SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, 'work') > 0;

SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, '$work') > 0;

SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, 'working') > 0;


SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, '$working') > 0;

--4.
SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, 'it') > 0;

-- Słowo "it" to stop-word, więc nie podlega indeksacji

--5.
SELECT *
FROM CTX_STOPLISTS;

-- DEFAULT_STOPLIST

--6.
SELECT *
FROM CTX_STOPWORDS;

--7.
DROP INDEX QUOTES_IDX;

CREATE INDEX QUOTES_IDX ON QUOTES(TEXT) INDEXTYPE IS CTXSYS.CONTEXT PARAMETERS ('stoplist CTXSYS.EMPTY_STOPLIST');

--8.
SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, 'it') > 0;

--9.
SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, 'fool and humans') > 0;

--10.
SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, 'fool and computer') > 0;

--11.
SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, '(FOOL AND COMPUTER) WITHIN SENTENCE', 1) > 0;

-- Sekcja SENTENCE jest niezdefiniowana

--12.
DROP INDEX QUOTES_IDX;

--13.
BEGIN
    CTX_DDL.CREATE_SECTION_GROUP('nullgroup', 'NULL_SECTION_GROUP');
    CTX_DDL.ADD_SPECIAL_SECTION('nullgroup', 'SENTENCE');
    CTX_DDL.ADD_SPECIAL_SECTION('nullgroup', 'PARAGRAPH');
END;

--14.
CREATE INDEX QUOTES_IDX ON QUOTES(TEXT) INDEXTYPE IS CTXSYS.CONTEXT PARAMETERS ('stoplist CTXSYS.EMPTY_STOPLIST section group nullgroup');

--15.
SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, '(fool and humans) WITHIN SENTENCE') > 0;

SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, '(fool and computer) WITHIN SENTENCE') > 0;

--16.
SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, 'humans') > 0;

-- Zwrócił non-humans, ponieważ '-' nie jest częścią indeksowanych tokenów

--17.
DROP INDEX QUOTES_IDX;

BEGIN
    CTX_DDL.CREATE_PREFERENCE('lex_z_m', 'BASIC_LEXER');
    CTX_DDL.SET_ATTRIBUTE('lex_z_m', 'printjoins', '-');
    CTX_DDL.SET_ATTRIBUTE('lex_z_m', 'index_text', 'YES');
END;

CREATE INDEX QUOTES_IDX ON QUOTES(TEXT) INDEXTYPE IS CTXSYS.CONTEXT PARAMETERS ('stoplist CTXSYS.EMPTY_STOPLIST section group nullgroup LEXER lex_z_m');

--18.
SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, 'humans') > 0;

--19.
SELECT *
FROM QUOTES
WHERE CONTAINS(TEXT, 'non\-humans') > 0;

--20.
BEGIN
    CTX_DDL.DROP_PREFERENCE('lex_z_m');
    CTX_DDL.DROP_SECTION_GROUP('nullgroup');
END;

DROP TABLE QUOTES;